common: &common
  adapter: postgresql
  encoding: unicode
  database: weblog
  pool: 5
  username: rodney
  password: qwerty

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
